INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-01', 'contabilidade-geral', 'Margem liquida (percentual)', 'multipla', 'calculo_percentual', '{"subjectLabel":"A empresa","numeratorLabel":"lucro liquido","denominatorLabel":"receita liquida","resultLabel":"a margem liquida","denominatorMin":20000,"denominatorMax":200000,"denominatorStep":100,"ratioMinPct":25,"ratioMaxPct":70,"explanation":"Margem liquida = lucro liquido dividido pela receita liquida, vezes 100."}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-02', 'contabilidade-geral', 'Indice de liquidez corrente (percentual)', 'multipla', 'calculo_percentual', '{"subjectLabel":"A empresa","numeratorLabel":"ativo circulante","denominatorLabel":"passivo circulante","resultLabel":"o indice de liquidez corrente","denominatorMin":10000,"denominatorMax":150000,"denominatorStep":100,"ratioMinPct":30,"ratioMaxPct":90,"explanation":"Liquidez corrente, em percentual, e o ativo circulante dividido pelo passivo circulante, vezes 100."}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-03', 'contabilidade-geral', 'Saldo final de caixa', 'lacuna_numerica', 'lacuna_numerica_formula', '{"formula":"caixa_liquido","promptTemplate":"Caixa inicial de R$ {a}, recebimentos de R$ {b} e pagamentos de R$ {c} no periodo. Qual o saldo final de caixa, em reais?","explanationTemplate":"Saldo final = caixa inicial + recebimentos - pagamentos = {a} + {b} - {c} = {resultado}.","aMin":1000,"aMax":20000,"bMin":500,"bMax":15000,"cMin":500,"cMax":25000,"decimalPlaces":2,"tolerance":0.01}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-04', 'contabilidade-geral', 'Depreciacao anual pelo metodo linear', 'lacuna_numerica', 'lacuna_numerica_formula', '{"formula":"depreciacao_linear","promptTemplate":"Um bem foi adquirido por R$ {a} e tem vida util estimada de {b} anos. Qual a depreciacao anual pelo metodo linear, em reais?","explanationTemplate":"Depreciacao anual = valor do bem dividido pela vida util = {a} / {b} = {resultado}.","aMin":6000,"aMax":240000,"bMin":2,"bMax":10,"cMin":0,"cMax":0,"decimalPlaces":2,"tolerance":0.01}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-05', 'contabilidade-geral', 'Ponto de equilibrio simplificado', 'multipla', 'equacao_linear', '{"contexto":"Os custos fixos mensais somados ao custo variavel por unidade vezes a quantidade vendida resultam na receita total.","aMin":5,"aMax":50,"xMin":10,"xMax":500,"bMin":100,"bMax":5000}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-06', 'contabilidade-geral', 'Markup sobre custo (equacao)', 'multipla', 'equacao_linear', '{"contexto":"O preco de venda e o custo do produto vezes o markup, somado a uma margem fixa em reais.","aMin":2,"aMax":20,"xMin":5,"xMax":200,"bMin":10,"bMax":900}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-07', 'contabilidade-geral', 'Regime de competencia', 'certo_errado', 'certo_errado_regra', '{"trueStatement":"Pelo regime de competencia, uma despesa e reconhecida no periodo em que e incorrida, mesmo que o pagamento ocorra depois.","falseStatement":"Pelo regime de competencia, uma despesa so e reconhecida no periodo em que e efetivamente paga, independentemente de quando ocorreu.","explanationTrue":"Correto: competencia reconhece despesas e receitas quando ocorrem, nao quando sao pagas ou recebidas.","explanationFalse":"Errado: isso descreve o regime de caixa, nao o de competencia. Competencia reconhece pelo fato gerador, nao pelo pagamento."}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-08', 'contabilidade-geral', 'Classificacao de ativo circulante', 'certo_errado', 'certo_errado_regra', '{"trueStatement":"Um ativo e classificado como circulante quando se espera realiza-lo, vende-lo ou consumi-lo no ciclo operacional normal da entidade ou em ate doze meses apos a data do balanco.","falseStatement":"Um ativo e classificado como circulante apenas quando a entidade pretende mante-lo por mais de doze meses apos a data do balanco.","explanationTrue":"Correto: o criterio e o ciclo operacional normal ou ate 12 meses, o que for maior, nao a intencao de manter por mais tempo.","explanationFalse":"Errado: isso inverte o criterio. Ativo de longo prazo (nao circulante) e que se espera manter por mais de 12 meses."}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-09', 'contabilidade-geral', 'Leitura de balanco patrimonial simplificado', 'dissertativa', 'interpretacao_texto', '{"texts":[{"context":"Balanco simplificado: Ativo circulante R$ 40.000 (caixa e estoque); Ativo nao circulante R$ 60.000 (imoveis e equipamentos). Passivo circulante R$ 25.000 (fornecedores); Passivo nao circulante R$ 15.000 (financiamento); Patrimonio liquido R$ 60.000.","prompt":"Com base no balanco acima, a empresa tem mais obrigacoes de curto prazo ou mais recursos proprios (patrimonio liquido)? Justifique com os numeros.","modelAnswer":"A empresa tem mais recursos proprios: patrimonio liquido de R$ 60.000 contra passivo circulante de R$ 25.000. O patrimonio liquido sozinho ja supera toda a divida de curto prazo.","explanation":"O ponto central e comparar patrimonio liquido (R$ 60.000) com passivo circulante (R$ 25.000), nao somar todas as obrigacoes."},{"context":"Balanco simplificado: Ativo circulante R$ 15.000; Ativo nao circulante R$ 85.000. Passivo circulante R$ 30.000; Passivo nao circulante R$ 40.000; Patrimonio liquido R$ 30.000.","prompt":"Essa empresa consegue pagar o passivo circulante so com o ativo circulante? O que isso indica sobre a liquidez de curto prazo dela?","modelAnswer":"Nao: o ativo circulante (R$ 15.000) e menor que o passivo circulante (R$ 30.000). Isso indica liquidez de curto prazo fraca - a empresa pode precisar vender ativo nao circulante ou buscar nova divida para honrar compromissos de curto prazo.","explanation":"O ponto central e comparar ativo circulante com passivo circulante; quando o ativo circulante e menor, a liquidez de curto prazo e um risco."}]}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('CG-MOD-10', 'contabilidade-geral', 'Interpretacao de DRE simplificada', 'dissertativa', 'interpretacao_texto', '{"texts":[{"context":"DRE simplificada: Receita liquida R$ 100.000; Custo dos produtos vendidos R$ (60.000); Lucro bruto R$ 40.000; Despesas operacionais R$ (25.000); Lucro liquido R$ 15.000.","prompt":"Qual foi o lucro bruto e o lucro liquido dessa empresa, e o que explica a diferenca entre os dois?","modelAnswer":"Lucro bruto de R$ 40.000 (receita menos custo dos produtos vendidos) e lucro liquido de R$ 15.000. A diferenca de R$ 25.000 sao as despesas operacionais, que ainda sao descontadas depois do lucro bruto.","explanation":"O ponto central e identificar que lucro bruto e antes das despesas operacionais, e lucro liquido e depois delas."},{"context":"DRE simplificada: Receita liquida R$ 80.000; Custo dos produtos vendidos R$ (70.000); Lucro bruto R$ 10.000; Despesas operacionais R$ (18.000); Prejuizo liquido R$ (8.000).","prompt":"Essa empresa deu lucro ou prejuizo no final? O lucro bruto positivo garante resultado final positivo? Explique.","modelAnswer":"A empresa deu prejuizo liquido de R$ 8.000, mesmo com lucro bruto positivo de R$ 10.000. Lucro bruto positivo nao garante resultado final positivo, porque as despesas operacionais (R$ 18.000) podem superar o lucro bruto.","explanation":"O ponto central e que lucro bruto positivo nao impede prejuizo liquido, se as despesas operacionais forem maiores que ele."}]}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
--> statement-breakpoint
INSERT INTO atlas_item_models (id, theme, title, kind, generator_key, params_json, bloom_level, difficulty_nominal, lifecycle_state, curated_by, created_at, updated_at)
VALUES ('DT-MOD-01', 'direito-tributario', 'Calculo de aliquota efetiva', 'multipla', 'calculo_percentual', '{"subjectLabel":"O contribuinte","numeratorLabel":"valor do imposto apurado","denominatorLabel":"base de calculo","resultLabel":"a aliquota efetiva aplicada","denominatorMin":5000,"denominatorMax":100000,"denominatorStep":100,"ratioMinPct":25,"ratioMaxPct":45,"explanation":"Aliquota efetiva = valor do imposto apurado dividido pela base de calculo, vezes 100."}', NULL, NULL, 'rascunho', 'abner', '2026-10-08T00:00:00.000Z', '2026-10-08T00:00:00.000Z');
